### ISSUE TITLE
Error when running tool

### ISSUE THREAD

**Issue by DrDinosaur** [milo2012/osintstalker#10]
root@Kali:~/Scripts/osintstalker-master# python fbstalker1.py 
Traceback (most recent call last):
  File "fbstalker1.py", line 60, in <module>
    driver = webdriver.Chrome(chrome_options=chromeOptions)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 64, in **init**
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 72, in **init**
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 114, in start_session
    'desiredCapabilities': desired_capabilities,
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 165, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 158, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: u'Unable to either launch or connect to Chrome. Please check that ChromeDriver is up-to-date. Using Chrome binary at: /usr/bin/google-chrome' 
root@Kali:~/Scripts/osintstalker-master# 

Chrome also pops up with an about:blank tab. Followed instructions in readme. Running Kali.

**Comment by milo2012** [comment]
Can you run the chromedriver executable ? Let me know if you get any errors.  I have this issue before and it was due to chromedriver not being able to run.

**Comment by DrDinosaur** [comment]
Once I manually start Chromedriver in a different terminal and let it continue to run, _that_ error goes away. Unfortunately, there are several others. I have never gotten this to work. It spits out this error when you are already authenicated:

root@Kali:~/Scripts/osintstalker-master# python fbstalker1.py -user xxx
[*] Username:   xxx
Traceback (most recent call last):
  File "fbstalker1.py", line 2041, in <module>
    options(sys.argv)
  File "fbstalker1.py", line 1985, in options
    mainProcess(user)
  File "fbstalker1.py", line 1763, in mainProcess
    loginFacebook(driver)
  File "fbstalker1.py", line 344, in loginFacebook
    assert "Welcome to Facebook" in driver.title
AssertionError

Somewhere in the process I'm pretty sure this blocked all images in Chrome. It says "this setting has been enforced by your administrator" and I have yet to find a fix. 

In the off chance you actually get the thing to start without an error, it doesn't work. All the URLs it visits in Chrome are invalid and it doesn't find anything. Here is an example before I stopped it:

root@Kali:~/Scripts/osintstalker-master# python fbstalker1.py -user xxx
[_] Username:   xxx
[_] Caching Profile Page: xxx
[_] Uid:  
[_] Caching Facebook Apps Used By: xxx

[_] Caching Pages Liked By: xxx
[_] Caching Videos Liked By: xxx
[_] Caching Photos Of: xxx
[_] Writing 0 record(s) to database table: photosOf
list index out of range
[*] Caching Photos By: xxx
^CTraceback (most recent call last):
  File "fbstalker1.py", line 2041, in <module>
    options(sys.argv)
  File "fbstalker1.py", line 1985, in options
    mainProcess(user)
  File "fbstalker1.py", line 1834, in mainProcess
    html = downloadPhotosOf(driver,uid)
  File "fbstalker1.py", line 946, in downloadPhotosOf
    time.sleep(3)
KeyboardInterrupt

Hopefully this potentially great and useful software will become stable in the near future. Oh, and this was running the latest version as of this comment. Thanks.

**Comment by milo2012** [comment]
Hi guys, I am building a bootable live CD.  It would be really useful if you could provide me some facebook usernames which you are having problems with so that I can run some tests on the live CD before I publish the live CD? 
Please email me if you are uncomfortable listing the test usernames here.  
That would really help me debug the issue as I did not encounter the error with the usernames that I tested.  The live CD will ensure that everyone is running on the same platform.  (Its just an idea). Please let me know what you think.

**Comment by milo2012** [comment]
I realized that I received the same error when the facebook_username and facebook_password are incorrect.  That's why i get all 0 in all results. I am not sure if you are having the same issues ? facebook_username is the same as the email address used to register for your facebook account.  I will write some code to handle the exception. Please try.

**Comment by jcope2013** [comment]
running into same issues, any progress ever made?

**Comment by 7S3V3N7** [comment]
Hey guys, i am getting this error myself.. any advice would be much appreciated! I have double checked the username and password in the python.py file and i did not spell anything wrong when editing the file.  

root@Kali:/opt/osintstalker# python fbstalker1.py -user https://www.facebook.com/(the users user name)1?fref=ts
[_] Username:   https://www.facebook.com/(the users username)?fref=ts
[_] Uid:    643117506
[*] Caching Facebook Apps Used By: https://www.facebook.com/(the users user name)1?fref=ts
Traceback (most recent call last):
  File "fbstalker1.py", line 2030, in <module>
    options(sys.argv)
  File "fbstalker1.py", line 1974, in options
    mainProcess(user)
  File "fbstalker1.py", line 1760, in mainProcess
    text_file = open(filename, "w")
IOError: [Errno 2] No such file or directory: 'https://www.facebook.com/(the users user name)1?fref=ts_apps.htm'

**Comment by marcelmfs** [comment]
You don't need to pass the whole URL, JUST the -user <username> , AGAIN: NOT -user http://..

**Comment by harayz** [comment]
did this ever get solved?
below are error messages that i get:

root@kali:~/Pentest/osintstalker# python fbstalker1.py johndoe
[*] Username:
[!] Problem converting username to uid

**Comment by dkv007** [comment]
HI,Please Help 

 File "fbstalker1.py", line 66
    conn = sqlite3.connect('facebook.db')
       ^
IndentationError: expected an indented block
