### ISSUE TITLE
Cannot Connect to Chrome Driver

### ISSUE THREAD

**Issue by loopyogden** [milo2012/osintstalker#13]
I am running Kali 64bit in a VM.  When I try to execute: python fbstalker1.py xxx

I get the following error....

Traceback (most recent call last):
File "fbstalker1.py", line 59, in <module>
driver = webdriver.Chrome(chrome_options=chromeOptions)

File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 59, in **init**    self.service.start()

File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/service.py", line 74, in start

raise WebDriverException("Can not connect to the ChromeDriver")
selenium.common.exceptions.WebDriverException: Message: 'Can not connect to the ChromeDriver' 

Since I am running 64 bit I installed the 64 bit Chrome browser and the 64 bit ChromeDriver.  Your instructions only mention the 32  bit ChromeDriver.  Any suggestions?

**Comment by loopyogden** [comment]
I was not able to download Chrome from:

wget http://95.31.35.30/chrome/pool/main/g/google-chrome-stable/google-chrome-stable_27.0.1453.93-r200836_amd64.deb

Link appears to be dead.  Just realized I am using a newer version of Chrome and wanted to make you aware in case this would cause issues with ChromeDriver.

**Comment by rsuciu-gsg** [comment]
One of my colleagues is getting this error as well. Unfortunately, I cannot reproduce it, so it's quite hard to try and debug.
He's using:
Chrome browser v55, 64bit
chromedriver 2.27
selenium 3.0.2

Any idea what might be the issue?

Thanks,
Ramona
