### ISSUE TITLE
IndexError after "Caching Pages Liked By: <User>"

### ISSUE THREAD

**Issue by th3l0b3** [milo2012/osintstalker#25]
Was able to fight thorugh the last issue I had and now am getting to the Caching Pages Liked and errors to this:

Traceback (most recent call last):
  File "fbstalker1.py", line 2030, in <module>
    options(sys.argv)
  File "fbstalker1.py", line 1974, in options
    mainProcess(user)
  File "fbstalker1.py", line 1790, in mainProcess
    dataList = parsePagesLiked(html)
  File "fbstalker1.py", line 1146, in parsePagesLiked
    pageCategory[count]
IndexError: list index out of range

**Comment by MaxTrance** [comment]
I am having this same issue.

**Comment by FLYBOY611** [comment]
Me as well, the exact same issue. Has anyone made any progress?

**Comment by emmanuelb23** [comment]
I just change pageName to pageCategory, because the problem is that var count exceeds the limit of index in the array pageCategory, but it seems like a patch however it works:

#for x in pageName:
    for x in pageCategory:
        m = r.search(str(x))
        if m:
            pageCategory[count]
            tempList.append([uid,x.text,pageCategory[count].text,m.group(1)])
        count+=1
    return tempList
