### ISSUE TITLE
ImportError: No module named tzlocal

### ISSUE THREAD

**Issue by ghost** [milo2012/osintstalker#31]
I keep getting :ImportError: No module named tzlocal" and I do not know what to do. I reinstalled the pip tzlocal and nothing happens.

**Comment by BlackOsint** [comment]
try: "sudo pip install tzlocal"

**Comment by ghost** [comment]
Thank you. That worked. Now I am getting a ImportError: No module named GraphMLParser. But there are a few threads that are already addressing that issue.

**Comment by huoshanwei** [comment]
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from vnpy.trader.engine import MainEngine
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vnpy-2.6.0-py3.7.egg/vnpy/trader/engine.py", line 45, in <module>
    from .setting import SETTINGS
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vnpy-2.6.0-py3.7.egg/vnpy/trader/setting.py", line 7, in <module>
    from tzlocal import get_localzone
ModuleNotFoundError: No module named 'tzlocal'

执行sudo pip install tzlocal也不行啊 还是会提示这个错误 求大神帮忙解决

**Comment by JeffQuantFin** [comment]
> Traceback (most recent call last): File "run.py", line 4, in from vnpy.trader.engine import MainEngine File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vnpy-2.6.0-py3.7.egg/vnpy/trader/engine.py", line 45, in from .setting import SETTINGS File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vnpy-2.6.0-py3.7.egg/vnpy/trader/setting.py", line 7, in from tzlocal import get_localzone ModuleNotFoundError: No module named 'tzlocal'
> 
> 执行sudo pip install tzlocal也不行啊 还是会提示这个错误 求大神帮忙解决

我也是。。请问你解决了吗？
