### ISSUE TITLE
No module named GraphMLParser

### ISSUE THREAD

**Issue by gamegoofs2** [milo2012/osintstalker#32]
File "fbstalker1.py", line 18, in <module>
    from pygraphml.GraphMLParser import *
ImportError: No module named GraphMLParser

After installing all the pre-reqs I run it and get this. I have worked around it by removing the .GraphMLParser portion, but I'm not sure if I am breaking the application by doing so. Am I missing something or is this a real issue?

**Comment by xlucagiordanox** [comment]
modify lines 18-21 in fbstalker1.py to this:
from pygraphml.graphml_parser import *
from pygraphml.graph import *
from pygraphml.node import *
from pygraphml.edge import *

**Comment by brandontict** [comment]
I am receiving the same error , Double checked dependences. Still no go. 

Lines 18-21 were already set  as above states. 

EDIT: 

Now I receive 

Traceback (most recent call last):
  File "fbstalker1.py", line 59, in <module>
    driver = webdriver.Chrome(chrome_options=chromeOptions)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 61, in **init**
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/service.py", line 88, in start
    os.path.basename(self.path) + "'")
selenium.common.exceptions.WebDriverException: Message: Can not connect to the 'chromedriver'

**Comment by brandontict** [comment]
After reinstalling chromedriver , 

raceback (most recent call last):
  File "fbstalker1.py", line 59, in <module>
    driver = webdriver.Chrome(chrome_options=chromeOptions)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 67, in **init**
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 87, in **init**
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 141, in start_session
    'desiredCapabilities': desired_capabilities,
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Unable to either launch or connect to Chrome. Please check that ChromeDriver is up-to-date. Using Chrome binary at: /usr/bin/google-chrome

google-chrome exists in /usr/bin/  . Although When i attempt to execute by itself, nothing happens. 

Will keep update, hope fully someone can benefit from this troubleshooting

**Comment by BlackOsint** [comment]
The problemas its selenium driver. You must download and configure

**Comment by PastaGringo** [comment]
No one found ? :(

**Comment by hitchou** [comment]
no solution ?
