### ISSUE TITLE
I can't get this to run for the life of me.

### ISSUE THREAD

**Issue by DgqwCupZ** [milo2012/osintstalker#5]
Kali linux wasn't happening so I thought I'd try an xp vm.

Traceback (most recent call last):
  File "E:\osintstalker\fbstalker.py", line 60, in <module>
    driver = webdriver.Chrome(chrome_options=chromeOptions)
  File "C:\Python26\lib\site-packages\selenium\webdriver\chrome\webdriver.py", l
ine 64, in **init**
    desired_capabilities=desired_capabilities)
  File "C:\Python26\lib\site-packages\selenium\webdriver\remote\webdriver.py", l
ine 71, in **init**
    self.start_session(desired_capabilities, browser_profile)
  File "C:\Python26\lib\site-packages\selenium\webdriver\remote\webdriver.py", l
ine 113, in start_session
    'desiredCapabilities': desired_capabilities,
  File "C:\Python26\lib\site-packages\selenium\webdriver\remote\webdriver.py", l
ine 164, in execute
    self.error_handler.check_response(response)
  File "C:\Python26\lib\site-packages\selenium\webdriver\remote\errorhandler.py"
, line 164, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: u'chrome not reachable\n
  (Driver info: chromedriver=2.4.226107,platform=Windows NT 5.1 SP3 x86)'

selenium-server-standalone-2.37.0.jar is up and running but nothing gets sent to it.

What am I supposed to put what here? Maybe what I have is wrong.

facebook_access_token="" < Where's the access token? Which cookie? datr I assumed but who knows.

facebook_username = "" < You want account name or will email do?
facebook_password = ""

global uid
uid = "" < What's this? the numeric account name?
username = "" < My account name again?
internetAccess = True
all_cookies = {}
reportFileName = ""

Oh yeah setuptools isn't going to work for python2.6 in linux as it's missing the sha256 module.

**Comment by milo2012** [comment]
It runs on python2.7 in Kali Linux now. Please refer to the README that i updated on here
https://github.com/milo2012/osintstalker/blob/master/README

facebook_access_token <- You can get an access_token here by creating a Facebook app.  https://developers.facebook.com/tools/access_token/

facebook_username <- email address
facebook_password

**Comment by milo2012** [comment]
You will need to download chromedriver

wget https://chromedriver.googlecode.com/files/chromedriver_linux64_23.0.1240.0.zip
unzip chromedriver_linux64_23.0.1240.0.zip
cp chromedriver /usr/local/
chmod 755 /usr/local/chromedriver

**Comment by milo2012** [comment]
Seems like there is some issues with chromedriver in Kali Linux. I am working on this.

**Comment by tomahock** [comment]
What permissions need the app required on facebook?

**Comment by milo2012** [comment]
I granted all during my test as I might have updates to the tool in future regarding further analysis and data gathering and I didn't want to keep changing them.

**Comment by milo2012** [comment]
I got it working on Kali Linux
The latest version of google chrome doesn't work with chromedriver, therefore you have to install the below older version.

If you are using 32 bit Kali Linux (run uname -r to find out) 
wget http://95.31.35.30/chrome/pool/main/g/google-chrome-stable/google-chrome-stable_27.0.1453.93-r200836_i386.deb

If you are using 64 bit Kali Linux (run uname -r to find out)
wget http://95.31.35.30/chrome/pool/main/g/google-chrome-stable/google-chrome-stable_27.0.1453.93-r200836_amd64.deb

Next, 
wget https://chromedriver.googlecode.com/files/chromedriver_linux32_23.0.1240.0.zip
unzip chromedriver_linux32_23.0.1240.0.zip
cp chromedriver /usr/local/chromedriver
chmod 777 /usr/local/chromedriver

**Comment by milo2012** [comment]
Remember to uninstall chrome browser (if you installed it earlier on)
apt-get remove chromium-browser

**Comment by DgqwCupZ** [comment]
Thanks for the update. I'm here now

 File "fbstalker.py", line 32, in <module>
    requests.adapters.DEFAULT_RETRIES = 10
AttributeError: 'module' object has no attribute 'adapters'

I think it's because I don't have an access token yet. I'll try later as they want a mobile phone.

**Comment by TheOncomingStorm** [comment]
I didn't have/need an access token and it worked for me.

**Comment by milo2012** [comment]
I received a number of emails that many people aren't sure how to get Facebook access token. 
Facebook access token is used in the code to convert username to user id.  I found that the profile picture link on profile page leaks the user id information. Therefore, facebook access token is not required for the tool anymore.

There are instances where there are no profile picture for the user. Therefore I am unable to find out the facebook id of the user from the profile picture.  This is a problem which I only found out yesterday.  If anyone of you know how to get the facebook ID of a user not username without using FQL, please let me know.

**Comment by wujekblade** [comment]
While working facebook returns this message:

Sorry, we couldn't understand this search. Please try saying this another way.

Can you help me to bypass this problem?

edit: And it returns empty UID. Something changed on FB?

**Comment by tomahock** [comment]
I got the same thing!

**Comment by modtastic** [comment]
Same thing here.

**Comment by DrDinosaur** [comment]
I am also getting this error.

**Comment by tasman35** [comment]
I have been trying for the past 4 days to get this to install and run.... i have followed the installed from github but i cant get it load...where can i find more help on this....

**Comment by marcelmfs** [comment]
I was able to clone and run it. But on kali linux only and it's dead slow, because of chromdriver and the need to run the browser in a desktop environment. I'd rather fork it to try to workaround phantomjs problems, than spending time trying to work this version out.
